<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('user_id');
            $table->string('email')->unique();
            $table->string('username')->nullable();
            $table->string('employee_id')->nullable();
            $table->string('join_date');
            $table->string('status')->nullable();
            $table->string('role_name')->nullable();
            $table->string('avatar')->nullable();
            $table->string('tgl_lahir')->nullable();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->rememberToken();
            $table->string('tema_aplikasi')->nullable();
            $table->string('status_online')->nullable();
            $table->timestamps();
        });

        DB::table('users')->insert([
            ['name'                         => 'Anggarda Bayu Wardana',
             'user_id'                      => 'ID_00001',
             'email'                        => 'bayuanggarda@gmail.com',
             'username'                     => 'Bayu',
             'employee_id'                  => '202102010704',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$eblmPakp26vR5ZaNm20anO.UJBKn3x0OQdGW9lzPKW8MOR6jo7ijq',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Nur Alfiyah Miftakhul Jannah',
             'user_id'                      => 'ID_00002',
             'email'                        => 'mjnuralfiyah@gmail.com',
             'username'                     => 'Alfi',
             'employee_id'                  => '202307010508',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$FOZxbGh6DapKoMceHJmF7elnYC2UQFAl/cUcGblwWul0c.EiKWfhi',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Annisa Jarizky Permata Alam',
             'user_id'                      => 'ID_00003',
             'email'                        => 'jarizkya@gmail.com',
             'username'                     => 'Annisa',
             'employee_id'                  => '202207010107',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$lkUhybhx2LENKu8cQ2IiEOIxfdsZLxa80UPdEEeziNek5DOnwb9RK',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Alvisi Aura Chandra',
             'user_id'                      => 'ID_00004',
             'email'                        => 'alvisiaura15@gmail.com',
             'username'                     => 'Alvisi',
             'employee_id'                  => '2023040106017',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$pZpqXwfUIxoNHdVYMEtdgeSvrdmIg1RLCLOUhsFQVBYxdY3yy34QS',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Agung Dewantara',
             'user_id'                      => 'ID_00005',
             'email'                        => 'agungdewan709@gmail.com',
             'username'                     => 'agung',
             'employee_id'                  => '2023090112010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$NGUGCOTB.TA3Dc49U1A8RuPb4NAJG3RSDmjyjHn67q0LPP0xvlL.6',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Alya Dwi Safitri',
             'user_id'                      => 'ID_00006',
             'email'                        => 'alyaadwisafitri@gmail.com',
             'username'                     => 'alya',
             'employee_id'                  => '2024030110010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$/BeoJjus5MwPkJHI3AfZiul43vD9TsOCy69bJ2Y0pFGQquPYpRjkW',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Andre Setiawan Ahmadi',
             'user_id'                      => 'ID_00007',
             'email'                        => 'Anxdre000@gmail.com',
             'username'                     => 'andre',
             'employee_id'                  => '2024030111010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$genusQg2hUsMS6gT6g943.lXpRJY/CNFXyOnzntvvb2lLIYiO06lW',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Muhammad Zulqarnain Hidayat',
             'user_id'                      => 'ID_00008',
             'email'                        => 'hidayat.zulqarnain@gmail.com',
             'username'                     => 'zulqarnain',
             'employee_id'                  => '2023090106010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$p0/S2qZVr.pzTcvGcD3NeeWzugKpp1apdRUDLwkE9qlAlibHkP41e',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Jovi Nisita Pratama',
             'user_id'                      => 'ID_00009',
             'email'                        => 'jovinisita@gmail.com',
             'username'                     => 'jovi',
             'employee_id'                  => '2023090106010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$nlZKcknCzlr7GBuWpaDCj.ZxuA8ReKW9ShVRfgHLs6zRff4N/8hGW',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Fiki Aviantono',
             'user_id'                      => 'ID_00010',
             'email'                        => 'fikia950@gmail.com',
             'username'                     => 'fiki',
             'employee_id'                  => '2023100103010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$aBt61cWm55/TBxJm6Jch/.xWjvFDbaFuuGultFS8auP3T5VqYeeY6',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Muhammad Imam Ghazali',
             'user_id'                      => 'ID_00011',
             'email'                        => 'imam.ghazali7@gmail.com',
             'username'                     => 'Imam',
             'employee_id'                  => '202104011202',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$hKnTmRvM2XUebaBgBgCD1eyQ97DTg0/46NL9WhmD0LQNusJ8J5Gj.',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Dinda Putri Ani',
             'user_id'                      => 'ID_00012',
             'email'                        => 'dnddesas@gmail.com',
             'username'                     => 'dinda',
             'employee_id'                  => '2024030112010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$SQd59NMfPFq1L7N6lWwNg.IzI.dakaT.z5QetJdJBggsHHdQkhrrS',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Tony Dwi Susanto',
             'user_id'                      => 'ID_00013',
             'email'                        => 'tony@pttati.co.id',
             'username'                     => 'tony',
             'employee_id'                  => '2023110100010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$S9mMWpiIsDAx5MaFcxqlr.QBLY9qpAh/uq84D6GJxeIe1HPBBzLHu',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Anisah Herdiyanti',
             'user_id'                      => 'ID_00014',
             'email'                        => 'anisah@pttati.co.id',
             'username'                     => 'anisah',
             'employee_id'                  => '2023110100010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$qioPbRtmB6W1hutXMUc3XeD9KMSnvz/6z7AaR9zo2jBCYAaJFyGZq',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Dimas Bagus Prasetya',
             'user_id'                      => 'ID_00015',
             'email'                        => 'dimasbagus9@gmail.com',
             'username'                     => 'dimas',
             'employee_id'                  => '2023110109010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$fpWVB0AgfyakJQ4YAEV5r.Vxmt3/blDOeRbEx3Ho0RS5r8rzFM4k.',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Olsavira Agsa Pratama',
             'user_id'                      => 'ID_00016',
             'email'                        => 'olsavira@gmail.com',
             'username'                     => 'sasa',
             'employee_id'                  => '2023050106010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$pEXoq3B5QAEB/bFSAVOGi./4ZSkLYoxHsJnJAT.u5cTw0ikiyPCVW',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Rahadian Bisma',
             'user_id'                      => 'ID_00017',
             'email'                        => 'bisma@pttati.co.id',
             'username'                     => 'bisma',
             'employee_id'                  => '2023110100010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$mW/cUnJ32JtYeOBnUi7WbuSX49uVyQKRdn.Z7fU5jarm9GoziMyr2',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Tiara Amalinda Prabawanti',
             'user_id'                      => 'ID_00018',
             'email'                        => 'tiara.amal@gmail.com',
             'username'                     => 'tiara',
             'employee_id'                  => '2024030106010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$IQASvsmMDZOZAmP5/8mTX.u3D2kUASufGcVlQtQqSh1Bt9j0T5xZ6',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Riris Amalia Sholikah',
             'user_id'                      => 'ID_00019',
             'email'                        => 'riris.aml.04@gmail.com',
             'username'                     => 'riris',
             'employee_id'                  => '2024030106010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$pCv0NvegGjXU3e9ARmRKguO0ZFEkQ0xzRYw5Ax11kCJhq8dUVjvwi',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Admintati',
             'user_id'                      => 'ID_00020',
             'email'                        => 'admintati@gmail.com',
             'username'                     => 'Admintati',
             'employee_id'                  => NULL,
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'Admin',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$fa7kSnvP01TLebcEKBAGwuzymOvph5C1GU.CabCjMWiiLP4qdq/Qi',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Firzaq Emir Pranowo',
             'user_id'                      => 'ID_00021',
             'email'                        => 'firzaqemirpranowo@gmail.com',
             'username'                     => 'Emir',
             'employee_id'                  => '202203010706',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$ZFR/AK..SncUnR0y8yABRevN7f8uO38rDMJYJfkutvpXS6ss/UJaO',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Evi Hidayatun Nafiah',
             'user_id'                      => 'ID_00022',
             'email'                        => 'evinafiahh@gmail.com',
             'username'                     => 'evi',
             'employee_id'                  => '2024030106010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$ny21ci/QIkgfSnbm9l5OMuNCGtETBbNixP/c/iiRuwopSfcv/ebG6',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Putri Regita Saptaningtias',
             'user_id'                      => 'ID_00023',
             'email'                        => 'putriregita79@gmail.com',
             'username'                     => 'regita',
             'employee_id'                  => '2024030106010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$CPza5KH0YO3imYvJUQD7/Oin6EmsdzSQFhrpJjSCNi4njUDcBgYi2',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Ainun Hasri',
             'user_id'                      => 'ID_00024',
             'email'                        => 'ainunhasri606@gmail.com',
             'username'                     => 'ainun',
             'employee_id'                  => '2024040103010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$B9UwQq5u95NMnxxV8rTA9ujuHBbUm0y1Qcv6moSU5U9DKOj8ADpQa',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Bhinti Nur Khasanah',
             'user_id'                      => 'ID_00025',
             'email'                        => 'bhinti.khasanah@gmail.com',
             'username'                     => 'Asa',
             'employee_id'                  => '2020020102012',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$SrQ7JNYOX0ZCjtK..PLt/.sTsYMjW5BgiE0ZFEgqvObrHjLt18R9m',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Muhammad Nabil Islam',
             'user_id'                      => 'ID_00026',
             'email'                        => 'nabilislam8@gmail.com',
             'username'                     => 'nabil',
             'employee_id'                  => '2023070112010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$0.aczpW5Z1YQe0TdUhPyFO.y5Ybm8zWl6hl4LMh9OPP7wdndELDra',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Daniel Hary Prasetyo',
             'user_id'                      => 'ID_00027',
             'email'                        => 'daniel@pttati.co.id',
             'username'                     => 'daniel',
             'employee_id'                  => '2023110100010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$e.hQo04N1VRJxCGjpN6QVu.aeT3BNjJhitLx8oX9xiB5JzVoTTxei',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Celvin Prananta Ginting',
             'user_id'                      => 'ID_00028',
             'email'                        => 'kelvin.p2504@gmail.com',
             'username'                     => 'kelvin',
             'employee_id'                  => '2024050107010',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$ksxP0gbZAkxP6sx9iG8QaOlH3ijJ9IZLhLUIzzF8VkNzkHKUlgjte',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Nur Aini Ersanti',
             'user_id'                      => 'ID_00029',
             'email'                        => 'nurainiersanti.if@gmail.com',
             'username'                     => 'Santi',
             'employee_id'                  => '202111010508',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$UJGZrSvzmUd7HsuIdUqHIu34asYL4EYCgKh16x6vt.tfVd8.Cstyi',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Astrid Dyssa Rachmawati',
             'user_id'                      => 'ID_00030',
             'email'                        => 'astriddyssa06@gmail.com',
             'username'                     => 'Astrid',
             'employee_id'                  => '2022090104014',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$XbaiiJ5KuTY04gta4JYH/eiUtuTKGaqe5.s6xMtKbKLOPdHDAtWwW',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Devi Thalia Agatha',
             'user_id'                      => 'ID_00031',
             'email'                        => 'devithaliaa@gmail.com',
             'username'                     => 'Devi',
             'employee_id'                  => '2023040103016',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$MAlOj4.6hGzh391.gvSBJ.tbYJOckVzL7fOr3JKYH5bOp1MzBkQ5q',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Dhya Aminaturrahmah',
             'user_id'                      => 'ID_00032',
             'email'                        => 'aminaturrahmahdhya2@gmail.com',
             'username'                     => 'Dhya',
             'employee_id'                  => '202110010302',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$RLkGC3YdPQ98MbWw9o7UsuAKC9xwir9EhwftIIuYcj5OdzLTI4dD6',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ],
            ['name'                         => 'Adeline Labaiqa Anindiani',
             'user_id'                      => 'ID_00033',
             'email'                        => 'adelinelabaiqa@gmail.com',
             'username'                     => 'Adel',
             'employee_id'                  => '2019030104012',
             'join_date'                    => now()->toDayDateTimeString(),
             'status'                       => 'Active',
             'role_name'                    => 'User',
             'avatar'                       => 'photo_defaults.jpg',
             'password'                     => '$2y$10$UDjTbau/T3OBdJeji1FT0ugAoIF28zFPc27TnjzPuawTnurpNfsli',
             'tema_aplikasi'                => 'Terang',
             'status_online'                => 'Offline',
             'created_at' => now(),
             'updated_at' => now()
            ]
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}