<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('mode_aplikasi', function (Blueprint $table) {
            $table->id();
            $table->string('name')->nullable();
            $table->string('user_id')->nullable();
            $table->string('email')->nullable();
            $table->string('tema_aplikasi')->nullable();
            $table->string('warna_sistem')->nullable();
            $table->string('warna_sistem_tulisan')->nullable();
            $table->string('warna_mode')->nullable();
            $table->string('tabel_warna')->nullable();
            $table->string('tabel_tulisan_tersembunyi')->nullable();
            $table->string('warna_dropdown_menu')->nullable();
            $table->string('ikon_plugin')->nullable();
            $table->string('bayangan_kotak_header')->nullable();
            $table->string('warna_mode_2')->nullable();
            $table->timestamps();
        });

        DB::table('mode_aplikasi')->insert([
            ['name'                         => 'Anggarda Bayu Wardana',
             'user_id'                      => 'ID_00001',
             'email'                        => 'bayuanggarda@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Nur Alfiyah Miftakhul Jannah',
             'user_id'                      => 'ID_00002',
             'email'                        => 'mjnuralfiyah@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Annisa Jarizky Permata Alam',
             'user_id'                      => 'ID_00003',
             'email'                        => 'jarizkya@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Alvisi Aura Chandra',
             'user_id'                      => 'ID_00004',
             'email'                        => 'alvisiaura15@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Agung Dewantara',
             'user_id'                      => 'ID_00005',
             'email'                        => 'agungdewan709@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Alya Dwi Safitri',
             'user_id'                      => 'ID_00006',
             'email'                        => 'alyaadwisafitri@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Andre Setiawan Ahmadi',
             'user_id'                      => 'ID_00007',
             'email'                        => 'Anxdre000@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Muhammad Zulqarnain Hidayat',
             'user_id'                      => 'ID_00008',
             'email'                        => 'hidayat.zulqarnain@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Jovi Nisita Pratama',
             'user_id'                      => 'ID_00009',
             'email'                        => 'jovinisita@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Fiki Aviantono',
             'user_id'                      => 'ID_00010',
             'email'                        => 'fikia950@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Muhammad Imam Ghazali',
             'user_id'                      => 'ID_00011',
             'email'                        => 'imam.ghazali7@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Dinda Putri Ani',
             'user_id'                      => 'ID_00012',
             'email'                        => 'dnddesas@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Tony Dwi Susanto',
             'user_id'                      => 'ID_00013',
             'email'                        => 'tony@pttati.co.id',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Anisah Herdiyanti',
             'user_id'                      => 'ID_00014',
             'email'                        => 'anisah@pttati.co.id',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Dimas Bagus Prasetya',
             'user_id'                      => 'ID_00015',
             'email'                        => 'dimasbagus9@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Olsavira Agsa Pratama',
             'user_id'                      => 'ID_00016',
             'email'                        => 'olsavira@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Rahadian Bisma',
             'user_id'                      => 'ID_00017',
             'email'                        => 'bisma@pttati.co.id',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Tiara Amalinda Prabawanti',
             'user_id'                      => 'ID_00018',
             'email'                        => 'tiara.amal@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Riris Amalia Sholikah',
             'user_id'                      => 'ID_00019',
             'email'                        => 'riris.aml.04@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Admintati',
             'user_id'                      => 'ID_00020',
             'email'                        => 'admintati@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Firzaq Emir Pranowo',
             'user_id'                      => 'ID_00021',
             'email'                        => 'firzaqemirpranowo@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Evi Hidayatun Nafiah',
             'user_id'                      => 'ID_00022',
             'email'                        => 'evinafiahh@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Putri Regita Saptaningtias',
             'user_id'                      => 'ID_00023',
             'email'                        => 'putriregita79@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Ainun Hasri',
             'user_id'                      => 'ID_00024',
             'email'                        => 'ainunhasri606@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Bhinti Nur Khasanah',
             'user_id'                      => 'ID_00025',
             'email'                        => 'bhinti.khasanah@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Muhammad Nabil Islam',
             'user_id'                      => 'ID_00026',
             'email'                        => 'nabilislam8@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Daniel Hary Prasetyo',
             'user_id'                      => 'ID_00027',
             'email'                        => 'daniel@pttati.co.id',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Celvin Prananta Ginting',
             'user_id'                      => 'ID_00028',
             'email'                        => 'kelvin.p2504@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Nur Aini Ersanti',
             'user_id'                      => 'ID_00029',
             'email'                        => 'nurainiersanti.if@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Astrid Dyssa Rachmawati',
             'user_id'                      => 'ID_00030',
             'email'                        => 'astriddyssa06@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Devi Thalia Agatha',
             'user_id'                      => 'ID_00031',
             'email'                        => 'devithaliaa@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Dhya Aminaturrahmah',
             'user_id'                      => 'ID_00032',
             'email'                        => 'aminaturrahmahdhya2@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ],
            ['name'                         => 'Adeline Labaiqa Anindiani',
             'user_id'                      => 'ID_00033',
             'email'                        => 'adelinelabaiqa@gmail.com',
             'tema_aplikasi'                => 'Terang',
             'warna_sistem'                 => NULL,
             'warna_sistem_tulisan'         => NULL,
             'warna_mode'                   => NULL,
             'tabel_warna'                  => NULL,
             'tabel_tulisan_tersembunyi'    => NULL,
             'warna_dropdown_menu'          => NULL,
             'ikon_plugin'                  => NULL,
             'bayangan_kotak_header'        => NULL,
             'warna_mode_2'                 => NULL,
            ]
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('mode_aplikasi');
    }
};