<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('daftar_pegawai', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('user_id');
            $table->string('email')->unique();
            $table->string('username')->nullable();
            $table->string('employee_id')->nullable();
            $table->string('role_name')->nullable();
            $table->string('avatar')->nullable();
            $table->string('tgl_lahir')->nullable();
            $table->timestamps();
        });

        // DB::table('daftar_pegawai')->insert([
        //     ['name'                         => 'Anggarda Bayu Wardana',
        //      'user_id'                      => 'ID_00001',
        //      'email'                        => 'bayuanggarda@gmail.com',
        //      'username'                     => 'Bayu',
        //      'employee_id'                  => '202102010704',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Nur Alfiyah Miftakhul Jannah',
        //      'user_id'                      => 'ID_00002',
        //      'email'                        => 'mjnuralfiyah@gmail.com',
        //      'username'                     => 'Alfi',
        //      'employee_id'                  => '202307010508',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Annisa Jarizky Permata Alam',
        //      'user_id'                      => 'ID_00003',
        //      'email'                        => 'jarizkya@gmail.com',
        //      'username'                     => 'Annisa',
        //      'employee_id'                  => '202207010107',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Alvisi Aura Chandra',
        //      'user_id'                      => 'ID_00004',
        //      'email'                        => 'alvisiaura15@gmail.com',
        //      'username'                     => 'Alvisi',
        //      'employee_id'                  => '2023040106017',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Agung Dewantara',
        //      'user_id'                      => 'ID_00005',
        //      'email'                        => 'agungdewan709@gmail.com',
        //      'username'                     => 'agung',
        //      'employee_id'                  => '2023090112010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Alya Dwi Safitri',
        //      'user_id'                      => 'ID_00006',
        //      'email'                        => 'alyaadwisafitri@gmail.com',
        //      'username'                     => 'alya',
        //      'employee_id'                  => '2024030110010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Andre Setiawan Ahmadi',
        //      'user_id'                      => 'ID_00007',
        //      'email'                        => 'Anxdre000@gmail.com',
        //      'username'                     => 'andre',
        //      'employee_id'                  => '2024030111010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Muhammad Zulqarnain Hidayat',
        //      'user_id'                      => 'ID_00008',
        //      'email'                        => 'hidayat.zulqarnain@gmail.com',
        //      'username'                     => 'zulqarnain',
        //      'employee_id'                  => '2023090106010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Jovi Nisita Pratama',
        //      'user_id'                      => 'ID_00009',
        //      'email'                        => 'jovinisita@gmail.com',
        //      'username'                     => 'jovi',
        //      'employee_id'                  => '2023090106010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Fiki Aviantono',
        //      'user_id'                      => 'ID_00010',
        //      'email'                        => 'fikia950@gmail.com',
        //      'username'                     => 'fiki',
        //      'employee_id'                  => '2023100103010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Muhammad Imam Ghazali',
        //      'user_id'                      => 'ID_00011',
        //      'email'                        => 'imam.ghazali7@gmail.com',
        //      'username'                     => 'Imam',
        //      'employee_id'                  => '202104011202',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Dinda Putri Ani',
        //      'user_id'                      => 'ID_00012',
        //      'email'                        => 'dnddesas@gmail.com',
        //      'username'                     => 'dinda',
        //      'employee_id'                  => '2024030112010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Tony Dwi Susanto',
        //      'user_id'                      => 'ID_00013',
        //      'email'                        => 'tony@pttati.co.id',
        //      'username'                     => 'tony',
        //      'employee_id'                  => '2023110100010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Anisah Herdiyanti',
        //      'user_id'                      => 'ID_00014',
        //      'email'                        => 'anisah@pttati.co.id',
        //      'username'                     => 'anisah',
        //      'employee_id'                  => '2023110100010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Dimas Bagus Prasetya',
        //      'user_id'                      => 'ID_00015',
        //      'email'                        => 'dimasbagus9@gmail.com',
        //      'username'                     => 'dimas',
        //      'employee_id'                  => '2023110109010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Olsavira Agsa Pratama',
        //      'user_id'                      => 'ID_00016',
        //      'email'                        => 'olsavira@gmail.com',
        //      'username'                     => 'sasa',
        //      'employee_id'                  => '2023050106010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Rahadian Bisma',
        //      'user_id'                      => 'ID_00017',
        //      'email'                        => 'bisma@pttati.co.id',
        //      'username'                     => 'bisma',
        //      'employee_id'                  => '2023110100010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Tiara Amalinda Prabawanti',
        //      'user_id'                      => 'ID_00018',
        //      'email'                        => 'tiara.amal@gmail.com',
        //      'username'                     => 'tiara',
        //      'employee_id'                  => '2024030106010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Riris Amalia Sholikah',
        //      'user_id'                      => 'ID_00019',
        //      'email'                        => 'riris.aml.04@gmail.com',
        //      'username'                     => 'riris',
        //      'employee_id'                  => '2024030106010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Admintati',
        //      'user_id'                      => 'ID_00020',
        //      'email'                        => 'admintati@gmail.com',
        //      'username'                     => 'Admintati',
        //      'employee_id'                  => NULL,
        //      'role_name'                    => 'Admin',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Firzaq Emir Pranowo',
        //      'user_id'                      => 'ID_00021',
        //      'email'                        => 'firzaqemirpranowo@gmail.com',
        //      'username'                     => 'Emir',
        //      'employee_id'                  => '202203010706',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Evi Hidayatun Nafiah',
        //      'user_id'                      => 'ID_00022',
        //      'email'                        => 'evinafiahh@gmail.com',
        //      'username'                     => 'evi',
        //      'employee_id'                  => '2024030106010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Putri Regita Saptaningtias',
        //      'user_id'                      => 'ID_00023',
        //      'email'                        => 'putriregita79@gmail.com',
        //      'username'                     => 'regita',
        //      'employee_id'                  => '2024030106010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Ainun Hasri',
        //      'user_id'                      => 'ID_00024',
        //      'email'                        => 'ainunhasri606@gmail.com',
        //      'username'                     => 'ainun',
        //      'employee_id'                  => '2024040103010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Bhinti Nur Khasanah',
        //      'user_id'                      => 'ID_00025',
        //      'email'                        => 'bhinti.khasanah@gmail.com',
        //      'username'                     => 'Asa',
        //      'employee_id'                  => '2020020102012',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Muhammad Nabil Islam',
        //      'user_id'                      => 'ID_00026',
        //      'email'                        => 'nabilislam8@gmail.com',
        //      'username'                     => 'nabil',
        //      'employee_id'                  => '2023070112010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Daniel Hary Prasetyo',
        //      'user_id'                      => 'ID_00027',
        //      'email'                        => 'daniel@pttati.co.id',
        //      'username'                     => 'daniel',
        //      'employee_id'                  => '2023110100010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Celvin Prananta Ginting',
        //      'user_id'                      => 'ID_00028',
        //      'email'                        => 'kelvin.p2504@gmail.com',
        //      'username'                     => 'kelvin',
        //      'employee_id'                  => '2024050107010',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Nur Aini Ersanti',
        //      'user_id'                      => 'ID_00029',
        //      'email'                        => 'nurainiersanti.if@gmail.com',
        //      'username'                     => 'Santi',
        //      'employee_id'                  => '202111010508',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Astrid Dyssa Rachmawati',
        //      'user_id'                      => 'ID_00030',
        //      'email'                        => 'astriddyssa06@gmail.com',
        //      'username'                     => 'Astrid',
        //      'employee_id'                  => '2022090104014',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Devi Thalia Agatha',
        //      'user_id'                      => 'ID_00031',
        //      'email'                        => 'devithaliaa@gmail.com',
        //      'username'                     => 'Devi',
        //      'employee_id'                  => '2023040103016',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Dhya Aminaturrahmah',
        //      'user_id'                      => 'ID_00032',
        //      'email'                        => 'aminaturrahmahdhya2@gmail.com',
        //      'username'                     => 'Dhya',
        //      'employee_id'                  => '202110010302',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ],
        //     ['name'                         => 'Adeline Labaiqa Anindiani',
        //      'user_id'                      => 'ID_00033',
        //      'email'                        => 'adelinelabaiqa@gmail.com',
        //      'username'                     => 'Adel',
        //      'employee_id'                  => '2019030104012',
        //      'role_name'                    => 'User',
        //      'avatar'                       => 'photo_defaults.jpg',
        //     ]
        // ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('daftar_pegawai');
    }
};